### ISSUE TITLE
messagePinned Only emits for messages sent after the client is logged in.

### ISSUE THREAD

**Issue by milanmdev** [Androz2091/discord-logs#105]
`messagePinned` Only emits for messages sent after the client is logged in. It should also emit for messages sent before the client logs in. 

Example:

Message A is sent before the client logged in. The bot logs in and a user pins Message A. The bot does nothing with that pinned message.

The bot logs in. Message A is sent. Message A is pinned & emitted.

**Comment by xHyroM** [comment]
Add partials MESSAGE to new Client

**Comment by Androz2091** [comment]
Yes @xHyroM is right
