### ISSUE TITLE
Cannot use discord-logs with a custom client

### ISSUE THREAD

**Issue by HunteRoi** [Androz2091/discord-logs#173]
Hello there!

I created a custom client (that actually extends `Discord.Client`). I want it to use discord-logs. 
```js
import { Client, ClientOptions } from 'discord.js';
import addDiscordLogsFramework from 'discord-logs';

class DatadropClient extends Client {
    constructor(options: ClientOptions) {
        super(options);
        addDiscordLogsFramework(this);
    }
}
```

Unfortunately, it seems that the library throws a TypeError whenever I try to pass it the `this` parameter.
I receive the following report from my logger: 
```
H:\git\personal\datadrop\node_modules\discord-logs\lib\index.js:47
        intents = new discord_js_1.Intents(client.options.intents);
                  ^

TypeError: discord_js_1.Intents is not a constructor
    at H:\git\personal\datadrop\node_modules\discord-logs\lib\index.js:47:19
    at step (H:\git\personal\datadrop\node_modules\discord-logs\lib\index.js:33:23)
    at Object.next (H:\git\personal\datadrop\node_modules\discord-logs\lib\index.js:14:53)
    at H:\git\personal\datadrop\node_modules\discord-logs\lib\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (H:\git\personal\datadrop\node_modules\discord-logs\lib\index.js:4:12)
    at module.exports (H:\git\personal\datadrop\node_modules\discord-logs\lib\index.js:41:54)
    at new DatadropClient (H:\git\personal\datadrop\build\src\datadrop.js:67:36)
    at Object.<anonymous> (H:\git\personal\datadrop\build\index.js:30:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

I checked your issues and saw that #171 and #169 talk about it. Both are closed by #172. Unfortunately, no release version has been made. Would it be possible to publish discord-logs@2.2.0 if possible?

**Comment by MegalithOffical** [comment]
same issue. I checked the npm but the new version didnt uploaded.
I tryed npm i git@github.com:Androz2091/discord-logs.git but it didnt work.

**Comment by TheAxioma** [comment]
I have same Issue.

**Comment by MegalithOffical** [comment]
I fixed the issue

**Comment by MegalithOffical** [comment]
Use npm i git@github.com:MegalithOffical/discord-logs.git

**Comment by MegalithOffical** [comment]
My forks works with v14 without any issues in my tests

**Comment by TheAxioma** [comment]
> My fork works with v14 without any issues in my tests

I got error 
npm ERR! git dep preparation failed

**Comment by MegalithOffical** [comment]
Hmh I will check when my electicity comeback.

**Comment by MegalithOffical** [comment]
Can you send full error please ?

**Comment by TheAxioma** [comment]
> Hmh I will check when my electicity comeback.

I fix error and Idownloaded what you wrote. 
Ty <3

**Comment by HunteRoi** [comment]
@Androz2091 hello there, would it be possible to release 2.0.2 please? It causes delay of some releases of other apps.
