### ISSUE TITLE
module isnt installing with windows

### ISSUE THREAD

**Issue by 0xtokuchi** [Androz2091/discord-logs#34]
when i using glitch its okey there is no problem but when i using windows i get this error my every project its not installing... i dont know why ? can u tell me how can i fix this
![image](https://user-images.githubusercontent.com/65005379/81459924-c7c0f180-91aa-11ea-9676-911aab55cb78.png)

**Comment by Androz2091** [comment]
Hello, it's because you don't have git installed on your computer.

* install git
* open git bash
* retry to install the package
