### ISSUE TITLE
voiceChannelJoin wasn't emited if member comes from other voice channel

### ISSUE THREAD

**Issue by Satont** [Androz2091/discord-logs#35]
If member comes from other voice channel, then voiceChannelJoin  will not be emited
Steps for reproduce:
```js
const Discord = require('discord.js')
const client = new Discord.Client()
const logs = require('discord-logs')
logs(client)

client.on("voiceChannelJoin", (member, channel) => {
  console.log(member.user.tag+" joined "+channel.name+"!");
});

client.login(TOKEN);
```
Join some channel, i.e called `channel1`, you will see it logged. After that join another voice channe, i.e `channel2`, and you will see it not logged.

Discord-logs: v1.7.5
Discord.js: v12.2

**Comment by Satont** [comment]
Ah, ok, i see. 

There is another event for handle those behavior, `voiceChannelSwitch`, right?

**Comment by Androz2091** [comment]
Yes, that's it!

**Comment by Satont** [comment]
Ok, thank you. :)
