### ISSUE TITLE
[Feature request] Invite event

### ISSUE THREAD

**Issue by misa-coder** [Androz2091/discord-logs#39]
Is there anyway you can add invite event. In which we can use them to get who invited the member
client.on('memberJoin', (member, invite) => {
console.log(member.user.tag+' invited by '+invite.creator)
})
Something like this will help us alot.

**Comment by Androz2091** [comment]
Why did you close the issue?

**Comment by misa-coder** [comment]
I just notice you already have a manage invite package. From where I can actually learn how to implement this. So... :sweat_smile:

**Comment by misa-coder** [comment]
Reopen the issue because I thought it maybe nice addon in this package

**Comment by misa-coder** [comment]
Is this project still active.....

**Comment by Androz2091** [comment]
Yes, and I think this will add to it, but I'm currently working on many other projects that take up a lot of my time. I don't despair, I will find time to develop this feature 😄

**Comment by HunteRoi** [comment]
If you need hep @Androz2091, you can make a call for contributors! I'd be happy to help :)

**Comment by Androz2091** [comment]
Okay so sorry for the delay but I'm closing this because I'm thinking about releasing a different package that will do the job
![Capture d’écran 2020-12-21 à 23 16 39](https://user-images.githubusercontent.com/42497995/102827389-c31c1700-43e2-11eb-9245-223adf902418.png)

**Comment by HunteRoi** [comment]
Is this already available? @Androz2091
