### ISSUE TITLE
Extend base emoji events

### ISSUE THREAD

**Issue by LWJerri** [Androz2091/discord-logs#40]
Does it possible extend default emoji events to have a user object

**Comment by Androz2091** [comment]
This could be added but at this time the only events supported are events that don't need any additional request (such as audit logs fetch). I don't know if it's a good idea to implement those type of events, don't hesitate to give your opinion here.

**Comment by Majoramari** [comment]
it would be cool to add events use audit logs to get the excuter etc

**Comment by HunteRoi** [comment]
I think it would be wonderful to have more events such as moderation ones (I think you need to scrap the audit logs at the moment to find more information about action, mod, target, reason etc.) and emojis'. This would benefit a lot!
