### ISSUE TITLE
voiceChannelUnmute

### ISSUE THREAD

**Issue by Abinawan** [Androz2091/discord-logs#45]
In voice channel Unmute, you have written

client.on("voiceChannelMute", (member, oldMuteType) => {
  console.log(member.user.tag+" become unmuted!");
});

But it should be:
client.on("voiceChannelUnmute", (member, oldMuteType) => {
  console.log(member.user.tag+" become unmuted!");
});
![image](https://user-images.githubusercontent.com/70474773/94834551-38a1c800-0430-11eb-8c39-622464d4e1d6.png)

**Comment by Androz2091** [comment]
True, thank you
