### ISSUE TITLE
Memory will goes overload sometimes (more often)

### ISSUE THREAD

**Issue by conver4y** [Androz2091/discord-logs#46]
Hey, how many events are you using? I check 2-3 hours and the memory increased to 1,3GB and the bot is private (one-server only)
Why?

**EDIT**
> possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

![image](https://user-images.githubusercontent.com/33544674/95475762-26d49d80-09b9-11eb-990c-08b89d09c976.png)

**Comment by conver4y** [comment]
![image](https://user-images.githubusercontent.com/33544674/95481501-a6fe0180-09bf-11eb-88d8-100022212122.png)

**Comment by Androz2091** [comment]
@conver4y it can be due to the fact that you use ```js
const logs = require('discord-logs');
logs(client);
```
in several places in your code
Do you?
