### ISSUE TITLE
Savoir qui a déconnecté qui

### ISSUE THREAD

**Issue by TakeFy** [Androz2091/discord-logs#63]
Salut ton framework est incroyable mais juste tu penses la possibilité d’ajouter quelque chose qui permet de savoir qui a déconnecté qui précisément ? Par exemple si quelqu’un déconnecte nous saurons la personne qui a été déconnectée.

**Comment by Androz2091** [comment]
Salut, il n'est pas possible de savoir cela (même en récupérant les logs du serveur), donc je ne pense pas pouvoir implémenter ça... Si quelqu'un a une idée ou si la fonctionnalité est ajoutée à Discord plus tard n'hésitez pas à rouvrir l'issue.
