### ISSUE TITLE
New Event: Accepting the rules.

### ISSUE THREAD

**Issue by sudis** [Androz2091/discord-logs#95]
It determines the events that will happen when someone accepts the rules. Like this:

```
client.on("rules", async (member, status) => {
console.log(status) // it must be True
})
```

**Comment by NamVr** [comment]
🤔 What rules are you talking about? Membership screening? You can use [`guildMemberEntered`](https://discord-logs.js.org/#event-8)

**Comment by sudis** [comment]
> 🤔 What rules are you talking about? Membership screening? You can use [`guildMemberEntered`](https://discord-logs.js.org/#event-8)

Four months ago it was not there.

**Comment by NamVr** [comment]
Nvm then, would you mind closing the issue :)
